export default class Auth {
    static SIGNIN_PROGRESS = 'SIGNIN_PROGRESS';
    static SIGNIN_SUCCESSFUL = 'SIGNIN_SUCCESSFUL';
    static SIGNIN_REJECTED = 'SIGNIN_REJECTED';
    static SIGNIN_PROGRESS_VERIFY = 'SIGNIN_PROGRESS_VERIFY';
    static SIGNIN_SUCCESSFUL_VERIFY = 'SIGNIN_SUCCESSFUL_VERIFY';
    static SIGNIN_REJECTED_VERIFY = 'SIGNIN_REJECTED_VERIFY';

    // Create Profile//
    static CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
    static CREATE_PRIFILE_ERROR = 'CREATE_PROFILE_ERROR';
    static CREATE_PROFILE_PROGRESS = 'CREATE_PROFILE_PROGRESS';


    // Profile Fetch //
    static GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
    static GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
    static GET_PROFILE_PROGRESS = 'GET_PROFILE_PROGRESS';




    /////////////// PUBLIC PROFILE //////////////////////
    static GET_ALL_USER_PUBLIC_SUCCESS = 'GET_ALL_USER_PUBLIC';
    static GET_ALL_USER_PUBLIC_ERROR = 'GET_ALL_USER_PUBLIC_ERROR';
    static GET_ALL_USER_PUBLIC_PROGRESS = 'GET_ALL_USER_PUBLIC_PROGRESS';
}